name: cd

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy pkgdown site
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install remotes
        run: Rscript -e "install.packages('remotes')"

      - name: Install dependencies
        run: Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Install pkgdown
        run: Rscript -e "install.packages('pkgdown')"

      - name: Deploy site
        run: Rscript -e "pkgdown::deploy_to_branch(new_process = FALSE)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
