name: ci-cd

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - name: Run R CMD check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning')"

      - name: Run testthat tests
        run: Rscript -e "testthat::test_dir('tests/testthat')"

  cd:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: pkgdown

      - name: Build and deploy pkgdown site
        run: Rscript -e "pkgdown::deploy_to_branch(new_process = FALSE)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
