name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "install.packages('rcmdcheck')"

      - name: Run R CMD check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning')"

      - name: Run testthat tests
        run: Rscript -e "testthat::test_dir('tests/testthat')"

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "install.packages('pkgdown')"

      - name: Build and deploy pkgdown site
        run: Rscript -e "pkgdown::deploy_to_branch(new_process = FALSE)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
